name: Deploy CodeGPM to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.CODEGPM_EC2_HOST }}
          username: ${{ secrets.CODEGPM_EC2_USER }}
          key: ${{ secrets.CODEGPM_EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Group-Project-Manager
            ./deploy.sh